title: Adhitya Putra
description: Blog Documentation
author: Adhitya Putra
logo: /idnewbie.github.io/static/img/avatar.png
github: https://github.com/idnewbie
about: Network Engineer |\sSystem Administration

baseurl: "https://idnewbie.github.io/"
url: "https://idnewbie.github.io/"

disqus_shortname: idnewbie
google_analytics: 

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
