title: John Smith
description: My Personal Blog
author: John Smith
logo: /idnewbie.github.io/static/img/avatar.png
github: https://github.com/ashutosh2k12
about: Freelance developer

baseurl: "https://idnewbie.github.io/"
url: "https://idnewbie.github.io/"

disqus_shortname: 
google_analytics: UA--1

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
